# Generated by Django 3.0.5 on 2020-05-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200504_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='Main_Course',
            new_name='topping1',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='Side_Dish',
            new_name='topping2',
        ),
    ]
